baseurl = "/"
title = "Software Engineer"
theme ="hugo-theme-developer-portfolio"
languageCode = "en-us"
enableEmoji = true
copyright = "© 2019 Jason Raimondi"

# disqusShortname = ""

pygmentsCodeFences=true
pygmentsUseClasses=true

defaultContentLanguage = "en"

pagination = 20

[Permalinks]
  post = "posts/:slug"

[Params]
  title = "jasonraimondi.com"
  description = "I am Jason Raimondi, a Software Engineer based in Los Angeles. My focus has been in web systems, building and deploying server and client web applications. I am a technologist and all around computer geek; give me a computer and I will be hacking in minutes, and occupied for days."
  twitter = "jsonmamondi"
  name = "Jason Raimondi"
  email = "jason@raimondi.us"
  resumePDF = "https://assets.jasonraimondi.com/resume/JasonRaimondi-Resume-3.2.6.pdf"
  resumeJSON = "https://assets.jasonraimondi.com/resume/resume.json"
  analyticsSnippet = """
<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
"""

[Params.ProfileURL]
  smallJPG = "https://assets.jasonraimondi.com/misc/me/avatar.jpg"
  smallWEBP = "https://assets.jasonraimondi.com/misc/me/avatar.webp"
  largeJPG = "https://assets.jasonraimondi.com/misc/me/avatar@2x.jpg"
  largeWEBP = "https://assets.jasonraimondi.com/misc/me/avatar@2x.webp"

[Params.MainMenu]
  title = "Projects"
[[Params.MainMenu.Link]]
  name = "Categories"
  url = "/categories"
[[Params.MainMenu.Link]]
  name = "About"
  url = "/about"
[[Params.MainMenu.Link]]
  name = "Uses"
  url = "/uses"

[Params.ProjectsMenu]
  title = "Projects"
[[Params.ProjectsMenu.Link]]
  name = "Traverse"
  url = "/posts/traverse-2-electric-boogaloo"
[[Params.ProjectsMenu.Link]]
  name = "Can I Poop?"
  url = "/posts/can-i-poop"
[[Params.ProjectsMenu.Link]]
  name = "Flipp"
  url = "/posts/flipp"

[Params.ExternalMenu]
  title = "Over There"
[[Params.ExternalMenu.Link]]
  name = "Gitea"
  url = "https://git.jasonraimondi.com/jason?tab=activity"
[[Params.ExternalMenu.Link]]
  name = "GitHub"
  url = "https://github.com/jasonraimondi"
[[Params.ExternalMenu.Link]]
  name = "GoodReads"
  url = "https://www.goodreads.com/jasonraimondi"
[[Params.ExternalMenu.Link]]
  name = "Leetcode"
  url = "https://leetcode.com/jasonraimondi"
[[Params.ExternalMenu.Link]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/jasonraimondi"
[[Params.ExternalMenu.Link]]
  name = "Vimeo"
  url = "https://vimeo.com/jasonraimondi"

[languages]
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
